format = """
[╭](fg:current_line)\
$os\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$fill\
$nodejs\
$dotnet\
$python\
$java\
$lua\
$golang\
$c\
$cmd_duration\
$shell\
$time\
$username\
$line_break\
$character\
"""

palette = 'rosepine'
add_newline = true

[palettes.rosepine]
foreground = '#e0def4'
background = '#191724'
current_line = '#403d52'
primary = '#403d52'
box = '#6e6a86'
blue = '#31748f'
cyan = '#9ccfd8'
green = '#56949f'
orange = '#f6c177'
brightorange = '#ff8700'
pink = '#ebbcba'
purple = '#c4a7e7'
red	= '#eb6f92'
yellow = '#f6c177'

[os]
format = '(fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CachyOS = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''


[directory]
format = '[─](fg:current_line)[](fg:green)[](fg:primary bg:green)[](fg:green bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = "󰉌"
truncation_symbol = ''
truncation_length = 2
read_only = '󱧴'
read_only_style = ''

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
"dev" = "󰲋"

[git_branch]
format = '[─](fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan bg:box)[ $branch](fg:foreground bg:box)[](fg:box bg:yellow)'
symbol = ''
disabled = true

[git_status]
disabled = true
format = '[( $all_status $ahead_behind)](fg:primary bg:yellow)[](fg:yellow bg:pink)'
conflicted = ' '
stashed = ' '
deleted = ' '
renamed = '󰑕 '
modified = ' '
typechanged = '󰕁 '
staged = '$count: '
untracked = '$count: '
diverged = ' $ahead_count $behind_count '
ahead = '$count: '
behind = '$count: '
up_to_date = ' '

[git_commit]
commit_hash_length = 5
tag_symbol = ' '
format = '[  $hash $tag](fg:primary bg:pink)[](fg:pink bg:background)'
disabled = true
only_detached = false
tag_disabled = false

[git_state]
disabled = true
format = '[─](fg:current_line)[](fg:red bg:background)[$state ](fg:primary bg:red)[$progress_current/$progress_total](fg:primary bg:red)[](fg:red bg:background)'
rebase = ''
merge = ''
revert = '󰕌'
cherry_pick = ''
bisect = ''
am = ''
am_or_rebase = ' or '

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 Node.js'
disabled = true

[dotnet]
format = '[─](fg:current_line)[](fg:purple)[$symbol](fg:primary bg:purple)[](fg:purple bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' .NET'
disabled = true

[python]
format = '[─](fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' python'
disabled = true

[java]
format = '[─](fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Java'
disabled = true

[lua]
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Lua'
disabled = true

[golang]
format = '[─](fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Go'

[c]
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' C'
disabled = true

[rust]
format = '[─](fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Rust'
disabled = true

[zig]
format = '[─](fg:current_line)[](fg:yellow)[$symbol](fg:primary bg:yellow)[](fg:yellow bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Rust'
disabled = true

[fill]
symbol = '·'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[·](fg:current_line)[](fg:orange)[](fg:primary bg:orange)[](fg:orange bg:brightorange)[ $duration ](fg:foreground bg:brightorange)[](fg:brightorange)'

[shell]
format = '[─](fg:current_line)[](fg:purple)[ ](fg:primary bg:purple)[](fg:purple bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = true

[time]
format = '[·](fg:current_line)[](fg:purple)[󰦖](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[username]
format = '[─](fg:current_line)[](fg:yellow)[ ](fg:primary bg:yellow)[](fg:yellow bg:box)[ $user](fg:foreground bg:box)[](fg:box) '
show_always = true
disabled = true

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[❯](fg:bold green)'
error_symbol = '[×](fg:bold red)'
